# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inventario.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'inventario.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10inventario.proto\"*\n\x0fProductoRequest\x12\x17\n\x0f\x63odigo_producto\x18\x01 \x01(\t\"d\n\x0cSucursalInfo\x12\x13\n\x0bsucursal_id\x18\x01 \x01(\t\x12\x17\n\x0fnombre_sucursal\x18\x02 \x01(\t\x12\x10\n\x08\x63\x61ntidad\x18\x03 \x01(\x05\x12\x14\n\x0cprecio_local\x18\x04 \x01(\x01\"\x82\x01\n\x10ProductoResponse\x12\x17\n\x0f\x63odigo_producto\x18\x01 \x01(\t\x12\x17\n\x0fnombre_producto\x18\x02 \x01(\t\x12\x19\n\x11stock_casa_matriz\x18\x03 \x01(\x05\x12!\n\nsucursales\x18\x04 \x03(\x0b\x32\r.SucursalInfo2O\n\x11InventarioService\x12:\n\x13ObtenerInfoProducto\x12\x10.ProductoRequest\x1a\x11.ProductoResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventario_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRODUCTOREQUEST']._serialized_start=20
  _globals['_PRODUCTOREQUEST']._serialized_end=62
  _globals['_SUCURSALINFO']._serialized_start=64
  _globals['_SUCURSALINFO']._serialized_end=164
  _globals['_PRODUCTORESPONSE']._serialized_start=167
  _globals['_PRODUCTORESPONSE']._serialized_end=297
  _globals['_INVENTARIOSERVICE']._serialized_start=299
  _globals['_INVENTARIOSERVICE']._serialized_end=378
# @@protoc_insertion_point(module_scope)
